### ISSUE TITLE
CSS基础规则 or CSS Base Rules

### ISSUE THREAD

**Issue by lanlin** [lanlin/notes#18]
### 选择器优先级
1. important声明 1,0,0,0
2. ID选择器          0,1,0,0
3. 类选择器          0,0,1,0
4. 伪类选择器      0,0,1,0
5. 属性选择器      0,0,1,0
6. 标签选择器      0,0,0,1
7. 伪元素选择器  0,0,0,1
8. 通配符选择器  0,0,0,0

### 选择器效率
1. ID选择器
2. 类选择器
3. 标签选择器
4. 相邻选择器
5. 子选择器
6. 后代选择器
7. 通配符选择器
8. 属性选择器
9. 伪类选择器

### 优先级高 != 效率高
`#id .class` 高于 `div#id p.class`

### 属性书写建议顺序
1. Display & Flow  
2. Positioning  
3. Dimensions  
4. Margins, Padding, Borders, Outline  
5. Typographic Styles  
6. Backgrounds  
7. Opacity, Cursors, Generated Content  
  
例子：  
```css
.demo {  
    display: ;  
    visibility: ;  
    float: ;  
    clear: ;  
  
    position: ;  
    top: ;  
    right: ;  
    bottom: ;  
    left: ;  
    z-index: ;  
  
    width: ;  
    min-width: ;  
    max-width: ;  
    height: ;  
    min-height: ;  
    max-height: ;  
    overflow: ;  
  
    margin: ;  
    margin-top: ;  
    margin-right: ;  
    margin-bottom: ;  
    margin-left: ;  
  
    padding: ;  
    padding-top: ;  
    padding-right: ;  
    padding-bottom: ;  
    padding-left: ;  
  
    border: ;  
    border-top: ;  
    border-right: ;  
    border-bottom: ;  
    border-left: ;  
  
    border-width: ;  
    border-top-width: ;  
    border-right-width: ;  
    border-bottom-width: ;  
    border-left-width: ;  
  
    border-style: ;  
    border-top-style: ;  
    border-right-style: ;  
    border-bottom-style: ;  
    border-left-style: ;  
  
    border-color: ;  
    border-top-color: ;  
    border-right-color: ;  
    border-bottom-color: ;  
    border-left-color: ;  
  
    outline: ;  
    list-style: ;  
  
    table-layout: ;  
    caption-side: ;  
    border-collapse: ;  
    border-spacing: ;  
    empty-cells: ;  
  
    font: ;  
    font-family: ;  
    font-size: ;  
    line-height: ;  
    font-weight: ;  
    text-align: ;  
    text-indent: ;  
    text-transform: ;  
    text-decoration: ;  
    letter-spacing: ;  
    word-spacing: ;  
    white-space: ;  
    vertical-align: ;  
    color: ;  
  
    background: ;  
    background-color: ;  
    background-image: ;  
    background-repeat: ;  
    background-position: ;  
  
    opacity: ;  
    cursor: ;  
    content: ;  
    quotes: ;  
}
```
